export enum Ifeatures {
  resetPassword = 'resetPassword',
  updatePhoneNumber = 'updatePhoneNumber',
  changePassword = 'changePassword',
  updateProfile = 'updateProfile',
  savedProjects = 'savedProjects',
  createCategory = 'create-category',
  updateCategory = 'update-category',
  removeCategory = 'remove-category',
  getGategoriesAdmin = 'get-gategories-admin',
  getAllTickets = 'get-all-tickets',
  updateTicket = 'update-ticket',
  removeTicket = 'remove-ticket',
  getTicket = 'get-ticket',
  createTerm = 'create-term',
  updateTerm = 'update-term',
  // plan
  createPlanHandler = 'create plan',
  updatePlanHandler = 'update plan',
  getPlanHandler = 'get plan',
  getAllPlansHandler = 'get all plans',
  removePlanHandler = 'remove plan',
  // roles
  createRoleHandler = 'create role',
  updateRoleHandler = 'update role',
  getRolesHandler = 'get roles',
  getRoleHandler = 'get role',
  removeRoleHandler = 'remove role',
}
