export enum PERMISSIONS {
  resetPassword = 'resetPassword',
  updatePhoneNumber = 'updatePhoneNumber',
  changePassword = 'changePassword',
  updateProfile = 'updateProfile',
  savedProjects = 'savedProjects',
  createCategory = 'create-category',
  updateCategory = 'update-category',
  removeCategory = 'remove-category',
  getAdminCategories = 'get-gategories-admin',
  createTicket = 'create ticket',
  getAllTickets = 'get-all-tickets',
  updateTicket = 'update-ticket',
  removeTicket = 'remove-ticket',
  getTicket = 'get-ticket',
  createTerm = 'create-term',
  updateTerm = 'update-term',
  // plan
  createPlanHandler = 'create plan',
  updatePlanHandler = 'update plan',
  getPlanHandler = 'get plan',
  getAllPlansHandler = 'get all plans',
  removePlanHandler = 'remove plan',
  // roles
  createRoleHandler = 'create role',
  updateRoleHandler = 'update role',
  getRolesHandler = 'get roles',
  getRoleHandler = 'get role',
  removeRoleHandler = 'remove role',
}

export const permissions = {
  auth: [
    PERMISSIONS.resetPassword,
    PERMISSIONS.updatePhoneNumber,
    PERMISSIONS.changePassword,
    PERMISSIONS.updateProfile,
  ],
  savedProjects: [PERMISSIONS.savedProjects],
  category: [
    PERMISSIONS.createCategory,
    PERMISSIONS.updateCategory,
    PERMISSIONS.updateCategory,
    PERMISSIONS.removeCategory,
    PERMISSIONS.getAdminCategories,
  ],
  ticket: [
    PERMISSIONS.createTicket,
    PERMISSIONS.getTicket,
    PERMISSIONS.getAllTickets,
    PERMISSIONS.removeTicket,
    PERMISSIONS.updateTicket,
  ],
  terms: [PERMISSIONS.createTerm, PERMISSIONS.updateTerm],
  plans: [
    PERMISSIONS.getPlanHandler,
    PERMISSIONS.createPlanHandler,
    PERMISSIONS.getAllPlansHandler,
    PERMISSIONS.removePlanHandler,
    PERMISSIONS.updatePlanHandler,
  ],
  roles: [
    PERMISSIONS.getRoleHandler,
    PERMISSIONS.getRolesHandler,
    PERMISSIONS.createRoleHandler,
    PERMISSIONS.updateRoleHandler,
    PERMISSIONS.updateRoleHandler,
    PERMISSIONS.removeRoleHandler,
  ],
};
