export enum MODELS {
  user = 'users',
  category = 'categories',
  plan = 'plans',
  role = 'roles',
  bookmark = 'bookmarks',
  term = 'terms',
  ticket = 'tickets',
  portfolioPost = 'portfolio-post',
  portfolioPostBooking = 'portfolio-post-booking',
  studioBooking = 'studio-booking',
  studioBookingBook = 'studio-booking-book',
  report = 'report',
  copyrights = 'copyrights',
  copyrightsBooking = 'copyrights-booking',
  projects = 'allProjects',
  messages = 'messages',
  notifications = 'notifications',
  teamProject = 'teamProjects',
  teamProjectBooking = 'teamProjects-booking',
  contracts = 'contracts',
  producer = 'producers',
  producerBooking = 'producer-booking',
  follow = 'follow'
}
