export enum PERMISSIONS {
  resetPassword = 'resetPassword',
  updatePhoneNumber = 'updatePhoneNumber',
  changePassword = 'changePassword',
  updateProfile = 'updateProfile',
  bookmarks = 'bookmarks',
  createCategory = 'create-category',
  updateCategory = 'update-category',
  removeCategory = 'remove-category',
  getAdminCategories = 'get-gategories-admin',
  createTicket = 'create ticket',
  getAllTickets = 'get-all-tickets',
  updateTicket = 'update-ticket',
  removeTicket = 'remove-ticket',
  getTicket = 'get-ticket',
  createTerm = 'create-term',
  updateTerm = 'update-term',
  // plan
  createPlanHandler = 'create plan',
  updatePlanHandler = 'update plan',
  getPlanHandler = 'get plan',
  getAllPlansHandler = 'get all plans',
  removePlanHandler = 'remove plan',
  // roles
  createRoleHandler = 'create role',
  updateRoleHandler = 'update role',
  getRolesHandler = 'get roles',
  getRoleHandler = 'get role',
  removeRoleHandler = 'remove role',
  // portfolio-post
  createProtfolioProjectHandler = 'create portfolio project',
  updatePortfolioProjectHandler = 'update portfolio project',
  removePortfolioProjectHandler = 'remove portfolio project',
  getCrmPortfolioProjectsHandlers = 'get crm portfolio projects',
  getAnalysisHandler = 'get analysis handler',
  // copyrights
  createCopyrightHandler = 'create copyright project',
  updateCopyrightHandler = 'update copyright project',
  removeCopyrightHandler = 'remove copyright project',
  getCrmCopyrightsHandlers = 'get crm copyright projects',
  getCopyrightAnalysisHandler = 'get copyright analysis handler',
  // studio-booking
  createStudioProjectHandler = 'create studio project',
  updateStudioProjectHandler = 'update studio project',
  removeStudioProjectHandler = 'remove studio project',
  getCrmStudioProjectsHandlers = 'get crm studio projects',
  getStudioAnalysisHandler = 'get studio analysis handler',
  // reports
  getAllReportsHandler = 'get all reports',
  getReportHandler = 'get report',
  updateReportHandler = 'update report',
  deleteReportHandler = 'delete report',
  // book project
  booking = 'booking',
}

export const permissions = {
  auth: [
    PERMISSIONS.resetPassword,
    PERMISSIONS.updatePhoneNumber,
    PERMISSIONS.changePassword,
    PERMISSIONS.updateProfile,
  ],
  bookmarks: [PERMISSIONS.bookmarks],
  category: [
    PERMISSIONS.createCategory,
    PERMISSIONS.updateCategory,
    PERMISSIONS.updateCategory,
    PERMISSIONS.removeCategory,
    PERMISSIONS.getAdminCategories,
  ],
  ticket: [
    PERMISSIONS.createTicket,
    PERMISSIONS.getTicket,
    PERMISSIONS.getAllTickets,
    PERMISSIONS.removeTicket,
    PERMISSIONS.updateTicket,
  ],
  terms: [PERMISSIONS.createTerm, PERMISSIONS.updateTerm],
  plans: [
    PERMISSIONS.getPlanHandler,
    PERMISSIONS.createPlanHandler,
    PERMISSIONS.getAllPlansHandler,
    PERMISSIONS.removePlanHandler,
    PERMISSIONS.updatePlanHandler,
  ],
  roles: [
    PERMISSIONS.getRoleHandler,
    PERMISSIONS.getRolesHandler,
    PERMISSIONS.createRoleHandler,
    PERMISSIONS.updateRoleHandler,
    PERMISSIONS.updateRoleHandler,
    PERMISSIONS.removeRoleHandler,
  ],
  portfolioPost: [
    PERMISSIONS.createProtfolioProjectHandler,
    PERMISSIONS.updatePortfolioProjectHandler,
    PERMISSIONS.removePortfolioProjectHandler,
    PERMISSIONS.getCrmPortfolioProjectsHandlers,
    PERMISSIONS.getAnalysisHandler,
  ],
  copyrights: [
    PERMISSIONS.createCopyrightHandler,
    PERMISSIONS.updateCopyrightHandler,
    PERMISSIONS.removeCopyrightHandler,
    PERMISSIONS.getCrmCopyrightsHandlers,
    PERMISSIONS.getCopyrightAnalysisHandler,
  ],
  studioBooking: [
    PERMISSIONS.createStudioProjectHandler,
    PERMISSIONS.updateStudioProjectHandler,
    PERMISSIONS.removeStudioProjectHandler,
    PERMISSIONS.getCrmStudioProjectsHandlers,
    PERMISSIONS.getStudioAnalysisHandler,
  ],
  booking: [PERMISSIONS.booking],
};
