export enum PERMISSIONS {
  resetPassword = 'resetPassword',
  updatePhoneNumber = 'updatePhoneNumber',
  changePassword = 'changePassword',
  updateProfile = 'updateProfile',
  bookmarks = 'bookmarks',
  createCategory = 'create-category',
  updateCategory = 'update-category',
  removeCategory = 'remove-category',
  getAdminCategories = 'get-gategories-admin',
  createTicket = 'create ticket',
  getAllTickets = 'get-all-tickets',
  updateTicket = 'update-ticket',
  removeTicket = 'remove-ticket',
  getTicket = 'get-ticket',
  createTerm = 'create-term',
  updateTerm = 'update-term',

  createUser = 'create user',
  updateUser = 'update user',
  blockUser = 'block user',
  unBlockUser = 'un block user',
  // plan
  createPlanHandler = 'create plan',
  updatePlanHandler = 'update plan',
  getPlanHandler = 'get plan',
  getAllPlansHandler = 'get all plans',
  removePlanHandler = 'remove plan',
  // roles
  createRoleHandler = 'create role',
  updateRoleHandler = 'update role',
  getRolesHandler = 'get roles',
  getRoleHandler = 'get role',
  removeRoleHandler = 'remove role',
  getAllPermissions = 'get all permissions',
  // project
  createProjectHandler = 'create project project',
  updateProjectHandler = 'update project project',
  removeProjectHandler = 'remove project project',
  getCrmProjectsHandlers = 'get crm project projects',
  getAnalysisHandler = 'get project analysis handler',
  // copyrights
  createCopyrightHandler = 'create copyright project',
  updateCopyrightHandler = 'update copyright project',
  removeCopyrightHandler = 'remove copyright project',
  getCrmCopyrightsHandlers = 'get crm copyright projects',
  getCopyrightAnalysisHandler = 'get copyright analysis handler',
  // Rental-booking
  createRentalProjectHandler = 'create Rental project',
  updateRentalProjectHandler = 'update Rental project',
  removeRentalProjectHandler = 'remove Rental project',
  getCrmRentalProject = 'get crm rental projects',
  getRentalAnalysisHandler = 'get Rental analysis handler',
  // reports
  getAllReportsHandler = 'get all reports',
  getReportHandler = 'get report',
  updateReportHandler = 'update report',
  deleteReportHandler = 'delete report',
  // book project
  booking = 'booking',
  // team project
  getCrmTeamProjectHandler = 'get crm team project crm',
  getTeamProjectAnalysisHandler = 'get team project analysis',
  deleteTeamProjectCreativeHandler = 'delete team project creative',
  updateTeamProjectCreativeHandler = 'update team project creative',
  createTeamProjectHandler = 'create team project',
  updateTeamProjectHandler = 'update team project',
  deleteTeamProjectHandler = 'delete team project',
  // producer
  getProducerAnalysis = 'get producer analysis',
  // rank
  createRankHandler = 'create rank',
  updateRankHandler = 'update rank',
  deleteRankHandler = 'delete rank',

  //setting
  createSettingHandler = 'create setting',
  updateSettingHandler = 'update setting',
  deleteSettingHandler = 'delete setting',

  // dashboard
  accessDashboard = 'access dashboard',
}

export const permissions = {
  auth: [
    PERMISSIONS.resetPassword,
    PERMISSIONS.updatePhoneNumber,
    PERMISSIONS.changePassword,
    PERMISSIONS.updateProfile,
  ],
  bookmarks: [PERMISSIONS.bookmarks],
  category: [
    PERMISSIONS.createCategory,
    PERMISSIONS.updateCategory,
    PERMISSIONS.updateCategory,
    PERMISSIONS.removeCategory,
    PERMISSIONS.getAdminCategories,
  ],
  ticket: [
    PERMISSIONS.createTicket,
    PERMISSIONS.getTicket,
    PERMISSIONS.getAllTickets,
    PERMISSIONS.removeTicket,
    PERMISSIONS.updateTicket,
  ],
  terms: [PERMISSIONS.createTerm, PERMISSIONS.updateTerm],
  plans: [
    PERMISSIONS.getPlanHandler,
    PERMISSIONS.createPlanHandler,
    PERMISSIONS.getAllPlansHandler,
    PERMISSIONS.removePlanHandler,
    PERMISSIONS.updatePlanHandler,
  ],
  roles: [
    PERMISSIONS.getRoleHandler,
    PERMISSIONS.getRolesHandler,
    PERMISSIONS.createRoleHandler,
    PERMISSIONS.updateRoleHandler,
    PERMISSIONS.updateRoleHandler,
    PERMISSIONS.removeRoleHandler,
    PERMISSIONS.getAllPermissions,
  ],
  Post: [
    PERMISSIONS.createProjectHandler,
    PERMISSIONS.updateProjectHandler,
    PERMISSIONS.removeProjectHandler,
    PERMISSIONS.getCrmProjectsHandlers,
    PERMISSIONS.getAnalysisHandler,
  ],
  copyrights: [
    PERMISSIONS.createCopyrightHandler,
    PERMISSIONS.updateCopyrightHandler,
    PERMISSIONS.removeCopyrightHandler,
    PERMISSIONS.getCrmCopyrightsHandlers,
    PERMISSIONS.getCopyrightAnalysisHandler,
  ],
  RentalBooking: [
    PERMISSIONS.createRentalProjectHandler,
    PERMISSIONS.updateRentalProjectHandler,
    PERMISSIONS.removeRentalProjectHandler,
    PERMISSIONS.getRentalAnalysisHandler,
    PERMISSIONS.getCrmRentalProject,
  ],
  booking: [PERMISSIONS.booking],
  teamProject: [
    PERMISSIONS.createTeamProjectHandler,
    PERMISSIONS.deleteTeamProjectCreativeHandler,
    PERMISSIONS.getTeamProjectAnalysisHandler,
    PERMISSIONS.getCrmTeamProjectHandler,
    PERMISSIONS.updateTeamProjectCreativeHandler,
    PERMISSIONS.deleteTeamProjectHandler,
    PERMISSIONS.updateTeamProjectHandler,
  ],
  rank: [
    PERMISSIONS.createRankHandler,
    PERMISSIONS.updateRankHandler,
    PERMISSIONS.deleteRankHandler,
  ],
  setting: [
    PERMISSIONS.createSettingHandler,
    PERMISSIONS.updateSettingHandler,
    PERMISSIONS.deleteSettingHandler,
  ],
  producer: [PERMISSIONS.getProducerAnalysis],
  dashboard: [PERMISSIONS.accessDashboard],
};
