# FROM node:alpine

# WORKDIR /app

# COPY package.json .
# RUN npm install --only=prod
# COPY . .

# CMD [ "npm" , "start" ]

FROM node:alpine

WORKDIR /app

COPY package.json .

RUN npm install

RUN npm install -g typescript

COPY . .

RUN npm run build

CMD ["npm", "start"]