apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_SERVER
            value: "mongodb-service"
          - name: ME_CONFIG_BASICAUTH_USERNAME
            value: "admin"
          - name: ME_CONFIG_BASICAUTH_PASSWORD
            value: "admin"
      restartPolicy: Always  

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: ingress-nginx
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
